### ISSUE TITLE
Movie search functionality

### ISSUE THREAD

**Issue by mfindlater** [mfindlater/MovieRental#2]
I have to make changes in MovieRentalSystem first then in frmMain.

- [ ] Add search method to MovieRentalSystem
- [ ] Search UI

**Comment by ComradeNapoleon** [comment]
permitting it won't conflict with your work, i was going to delete the search bar for Customers

**Comment by mfindlater** [comment]
Can't yet, I'm fixing the view rental stuff in the form, almost ready to commit it

**Comment by mfindlater** [comment]
You can remove customer search now, I started widening the form but I didn't move anything yet.
